# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
get_dict <- function() {
    .Call('_dutchsent_get_dict', PACKAGE = 'dutchsent')
}

#' @title C++ wrapper around main fun in get_words.R
#' @description Function extracts words from text.
#' @param str Character. For example, a sentence like "Mijn naam is Gerard. Ik ben een goochelaar".
#' @return Character Vector.
#'
get_words_Cpp <- function(str) {
    .Call('_dutchsent_get_words_Cpp', PACKAGE = 'dutchsent', str)
}

