# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LCSubStr <- function(X, Y) {
    .Call('_dutchsent_LCSubStr', PACKAGE = 'dutchsent', X, Y)
}

LCS_ratio <- function(s1, s2) {
    .Call('_dutchsent_LCS_ratio', PACKAGE = 'dutchsent', s1, s2)
}

#' Calculate for each string the Longest Common Substring given a set of target strings.
#'
#' @param strings String Vector.
#' @param targets String Vector.
#' @export
most_similar_LCS <- function(strings, targets) {
    .Call('_dutchsent_most_similar_LCS', PACKAGE = 'dutchsent', strings, targets)
}

damerau_levenshtein <- function(A, B) {
    .Call('_dutchsent_damerau_levenshtein', PACKAGE = 'dutchsent', A, B)
}

damerau_levenshtein_ratio <- function(s1, s2) {
    .Call('_dutchsent_damerau_levenshtein_ratio', PACKAGE = 'dutchsent', s1, s2)
}

#' Calculate for each string the normalized Damerau-Levenshtein Distance given a set of target strings.
#'
#' @param strings String Vector.
#' @param targets String Vector.
#' @export
most_similar_DL <- function(strings, targets) {
    .Call('_dutchsent_most_similar_DL', PACKAGE = 'dutchsent', strings, targets)
}

#' @export
get_sentiment <- function(text, dict_words, dict_scores, cutoff_levenstein, cutoff_sim_ratio) {
    .Call('_dutchsent_get_sentiment', PACKAGE = 'dutchsent', text, dict_words, dict_scores, cutoff_levenstein, cutoff_sim_ratio)
}

#' @title C++ wrapper around main fun in get_words.R
#' @description Function extracts words from text.
#' @param str Character. For example, a sentence like "Mijn naam is Gerard. Ik ben een goochelaar".
#' @return Character Vector.
#'
get_words_Cpp <- function(str) {
    .Call('_dutchsent_get_words_Cpp', PACKAGE = 'dutchsent', str)
}

#' @title Find the max indices given a list of edit distances.
#' @description Function is designed to find the min indices in a list of numeric vectors.
#' The numeric vectors consist of edit distances, numeric values.
#' @param list_of_edit_distances A list of numeric vectors.
#' @param words CharacterVector. List of words.
#' @param dict_words CharacterVector. Word dictionary.
#' @param cutoff_levenstein Integer. Levenshtein Distance cutoff.
#' @param cutoff_LCS Double. Least Common Substring ratio cutoff.
#' @return IntegerVector
#' @export
dict_idx_lookup <- function(list_of_edit_distances, words, dict_words, cutoff_levenstein, cutoff_sim_ratio) {
    .Call('_dutchsent_dict_idx_lookup', PACKAGE = 'dutchsent', list_of_edit_distances, words, dict_words, cutoff_levenstein, cutoff_sim_ratio)
}

jaro_distance <- function(s1, s2) {
    .Call('_dutchsent_jaro_distance', PACKAGE = 'dutchsent', s1, s2)
}

#' Calculate for each string the Jaro Distance given a set of target strings.
#'
#' @param strings String Vector.
#' @param targets String Vector.
#' @export
most_similar_jaro <- function(strings, targets) {
    .Call('_dutchsent_most_similar_jaro', PACKAGE = 'dutchsent', strings, targets)
}

#' @export
jaro_winkler_distance <- function(str1, str2) {
    .Call('_dutchsent_jaro_winkler_distance', PACKAGE = 'dutchsent', str1, str2)
}

#' @title Calculate for each string the Jaro Winkler Distance given a set of target strings.
#' @param strings String Vector.
#' @param targets String Vector.
#' @export
most_similar_jw <- function(strings, targets) {
    .Call('_dutchsent_most_similar_jw', PACKAGE = 'dutchsent', strings, targets)
}

levenstein_distance <- function(s1, s2) {
    .Call('_dutchsent_levenstein_distance', PACKAGE = 'dutchsent', s1, s2)
}

#' @title Calculate for each string the normalized Levenshtein distance given a set of target strings.
#' @param strings String Vector.
#' @param targets String Vector.
#' @export
#' @examples
#' words <- c("stomme", "goede")
#' targets <- c("goed", "stom", "ziek")
#' most_similar_levenstein(words, targets)
most_similar_levenstein <- function(strings, targets) {
    .Call('_dutchsent_most_similar_levenstein', PACKAGE = 'dutchsent', strings, targets)
}

#' @export
load_dict <- function() {
    .Call('_dutchsent_load_dict', PACKAGE = 'dutchsent')
}

load_negation_words <- function() {
    .Call('_dutchsent_load_negation_words', PACKAGE = 'dutchsent')
}

load_stopwords <- function() {
    .Call('_dutchsent_load_stopwords', PACKAGE = 'dutchsent')
}

#' @export
dict_index <- function(words, dict_words, cutoff_levenstein, cutoff_sim_ratio) {
    .Call('_dutchsent_dict_index', PACKAGE = 'dutchsent', words, dict_words, cutoff_levenstein, cutoff_sim_ratio)
}

#' @title Find the sentiment score of a word in the sentiment dictionary.
#' @param words CharacterVector. Vector of words.
#' @param dict_words CharacterVector. A word dictionary.
#' @param dict_scores IntegerVector. Scores for each word in the dictionary.
#' @param cutoff Integer. The number of single-character edits required
#' to change a word in the target word.
#' @return IntegerVector. Sentiment scores for each word, 0 if no match was found.
#' @examples
#' words <- c("stomme", "goede")
#' algorithmic_search_dict(words, dict$word, dict$score, 2, .3)
#' @export
algorithmic_search_dict <- function(words, dict_words, dict_scores, cutoff_levenstein, cutoff_sim_ratio) {
    .Call('_dutchsent_algorithmic_search_dict', PACKAGE = 'dutchsent', words, dict_words, dict_scores, cutoff_levenstein, cutoff_sim_ratio)
}

#' @title Find the most similar word in the dictionary.
#' @param words CharacterVector. Vector of words.
#' @param dict_words CharacterVector. A word dictionary.
#' @param dict_scores IntegerVector. Scores for each word in the dictionary.
#' @param cutoff Integer. The number of single-character edits required
#' to change a word in the target word.
#' @export
most_similar_word <- function(words, dict_words, dict_scores, cutoff_levenstein, cutoff_sim_ratio) {
    .Call('_dutchsent_most_similar_word', PACKAGE = 'dutchsent', words, dict_words, dict_scores, cutoff_levenstein, cutoff_sim_ratio)
}

#' @title Remove words from a vector of words.
#' @param words. A vector of single words.
#' @param word_list. A vector with words that you want to remove.
#' @export
#' @examples
#' some_words <- c("hallo", "there", "die")
#' remove <- c("zo", "die")
#' remove_words(some_words, remove)
remove_words <- function(words, word_list) {
    .Call('_dutchsent_remove_words', PACKAGE = 'dutchsent', words, word_list)
}

#' @title Load your dutch sentiment dictionary and search a word in it.
#' @description Find the sentiment score of a word in the sentiment dictionary.
#' @param w CharacterVector. Words you want to test, each in a separate vector.
#' @param words CharacterVector. Words from your sentiment dictionary.
#' @param scores IntegerVector. Scores that belong to each word in your dict.
#' @examples
#' dict <- load_dict()
#' words <- c("goed", "leuk")
#' search_dict(words, dict$word, dict$score)
#' @export
search_dict <- function(w, words, scores) {
    .Call('_dutchsent_search_dict', PACKAGE = 'dutchsent', w, words, scores)
}

#' @title Check whether words are in a word list.
#' @description Returns `TRUE` if a word or vector of words
#' are in a word list. Otherwise it returns FALSE.
#' @param word_list Vector of Characters, each a word.
#' @param words Vector of Characters, each a word.
#' @export
str_contains <- function(words, word_list) {
    .Call('_dutchsent_str_contains', PACKAGE = 'dutchsent', words, word_list)
}

str_len <- function(x) {
    .Call('_dutchsent_str_len', PACKAGE = 'dutchsent', x)
}

str_len_vectorized <- function(x) {
    .Call('_dutchsent_str_len_vectorized', PACKAGE = 'dutchsent', x)
}

#' @title Count how many letters from a word occur in a target.
#' @param word CharacterVector.
#' @param target CharacterVector.
#' @export
str_match <- function(word, target) {
    .Call('_dutchsent_str_match', PACKAGE = 'dutchsent', word, target)
}

#' @export
to_lowercase <- function(str) {
    .Call('_dutchsent_to_lowercase', PACKAGE = 'dutchsent', str)
}

